name: Setup Poetry
description: Setup Poetry
inputs:
  python-version:
    required: true
    default: "3.10"
  poetry-version:
    required: true
    default: "1.7.1"
  pip-cache-dir:
    required: true
    default: ~/.cache/pip
  poetry-cache-dir:
    required: true
    default: ~/.cache/pypoetry
  poetry-data-dir:
    required: true
    default: ~/.local/share/pypoetry
  shell:
    required: true
    default: bash
runs:
  using: composite
  steps:
    - name: Set environment variables
      shell: ${{ inputs.shell }}
      run: |
        echo "PYTHON_VERSION=${{ inputs.python-version }}" >> $GITHUB_ENV
        echo "POETRY_VERSION=${{ inputs.poetry-version }}" >> $GITHUB_ENV
        echo "PIP_CACHE_DIR=${{ inputs.pip-cache-dir }}" >> $GITHUB_ENV
        echo "POETRY_CACHE_DIR=${{ inputs.poetry-cache-dir }}" >> $GITHUB_ENV
        echo "POETRY_DATA_DIR=${{ inputs.poetry-data-dir }}" >> $GITHUB_ENV

    - name: Cache pip caches
      uses: actions/cache@v3
      with:
        path: ${{ env.PIP_CACHE_DIR }}
        key: pip-cache-${{ runner.os }}-python${{ inputs.python-version }}-poetry${{ inputs.poetry-version }}
        restore-keys: |
          pip-cache-${{ runner.os }}-python${{ inputs.python-version }}-poetry${{ inputs.poetry-version }}
          pip-cache-${{ runner.os }}-python${{ inputs.python-version }}

    - name: Cache poetry caches
      uses: actions/cache@v3
      with:
        path: ${{ env.POETRY_CACHE_DIR }}
        key: poetry-cache-${{ runner.os }}-python${{ inputs.python-version }}-poetry${{ inputs.poetry-version }}-${{ hashFiles('poetry.lock') }}
        restore-keys: |
          poetry-cache-${{ runner.os }}-python${{ inputs.python-version }}-poetry${{ inputs.poetry-version }}-${{ hashFiles('poetry.lock') }}
          poetry-cache-${{ runner.os }}-python${{ inputs.python-version }}-poetry${{ inputs.poetry-version }}

    - name: Cache packages
      uses: actions/cache@v3
      with:
        path: ${{ env.POETRY_DATA_DIR }}
        key: poetry-local-${{ runner.os }}-python${{ inputs.python-version }}-poetry${{ inputs.poetry-version }}-${{ hashFiles('poetry.lock') }}
        restore-keys: |
          poetry-local-${{ runner.os }}-python${{ inputs.python-version }}-poetry${{ inputs.poetry-version }}-${{ hashFiles('poetry.lock') }}
          poetry-local-${{ runner.os }}-python${{ inputs.python-version }}-poetry${{ inputs.poetry-version }}
          poetry-local-${{ runner.os }}-python${{ inputs.python-version }}

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Run image
      uses: abatilo/actions-poetry@v2
      with:
        poetry-version: ${{ inputs.poetry-version }}

